// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27enwedy1_ARt6V5SAdh6E6kQr-QbYYY',
    appId: '1:828562772715:web:81c961e44e00fe160e24ae',
    messagingSenderId: '828562772715',
    projectId: 'fl-22-auth-f881d',
    authDomain: 'fl-22-auth-f881d.firebaseapp.com',
    storageBucket: 'fl-22-auth-f881d.appspot.com',
    measurementId: 'G-7GJQD5BE9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANo7_rfw7LmLBvGXBx2KK9FKEiX9i8xbE',
    appId: '1:828562772715:android:6b3771f76d3501280e24ae',
    messagingSenderId: '828562772715',
    projectId: 'fl-22-auth-f881d',
    storageBucket: 'fl-22-auth-f881d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdgaB9Mo_W8Upd_fXF7QH4KQLMWz8kBpI',
    appId: '1:828562772715:ios:8cead231750c08a40e24ae',
    messagingSenderId: '828562772715',
    projectId: 'fl-22-auth-f881d',
    storageBucket: 'fl-22-auth-f881d.appspot.com',
    iosBundleId: 'com.pdp.fl22Auth',
  );
}
